package xds

import (
	"context"
	"errors"
	"strings"
	"testing"

	yamlv3 "gopkg.in/yaml.v3"

	"github.com/linkinghack/envoy-standalone-gateway/internal/compile/envoycheck"
)

// validOpts 是一份合法的渲染参数（tcp admin 形态），各测试按需覆盖字段。
func validOpts() BootstrapOpts {
	return BootstrapOpts{
		NodeID:       "esgw-node",
		NodeCluster:  "esgw",
		XDSListen:    "127.0.0.1:18000",
		AdminAddress: "127.0.0.1:9901",
	}
}

// parseBootstrapYAML 把产物解析回 map 供断言（顺带验证产物是合法 YAML）。
func parseBootstrapYAML(t *testing.T, b []byte) map[string]any {
	t.Helper()
	var v map[string]any
	if err := yamlv3.Unmarshal(b, &v); err != nil {
		t.Fatalf("rendered output is not valid YAML: %v\n%s", err, b)
	}
	return v
}

// dig 按路径逐层下钻 map，任一层缺失即 fail。
func dig(t *testing.T, m map[string]any, path ...string) any {
	t.Helper()
	var cur any = m
	for _, p := range path {
		mm, ok := cur.(map[string]any)
		if !ok {
			t.Fatalf("path %v: %q is not a map", path, p)
		}
		cur, ok = mm[p]
		if !ok {
			t.Fatalf("path %v: missing key %q", path, p)
		}
	}
	return cur
}

func TestRenderBootstrapHeader(t *testing.T) {
	b, err := RenderBootstrap(validOpts())
	if err != nil {
		t.Fatal(err)
	}
	// 文件头与 static.Render 同款首行；写 node_id 而非 config_version
	// （接入 bootstrap 与配置版本无关，见 T4 进展记录）。
	if !strings.HasPrefix(string(b), "# Generated by esgw. DO NOT EDIT.\n# node_id: esgw-node\n") {
		t.Fatalf("missing header comments:\n%s", b)
	}
	if strings.Contains(string(b), "config_version") {
		t.Fatalf("bootstrap must not carry config_version:\n%s", b)
	}
}

func TestRenderBootstrapDefaults(t *testing.T) {
	opts := validOpts()
	opts.NodeID = ""
	opts.NodeCluster = ""
	b, err := RenderBootstrap(opts)
	if err != nil {
		t.Fatal(err)
	}
	doc := parseBootstrapYAML(t, b)
	if got := dig(t, doc, "node", "id"); got != "esgw-node" {
		t.Fatalf("node.id = %v, want esgw-node", got)
	}
	if got := dig(t, doc, "node", "cluster"); got != "esgw" {
		t.Fatalf("node.cluster = %v, want esgw", got)
	}
}

func TestRenderBootstrapAdminUnix(t *testing.T) {
	opts := validOpts()
	opts.AdminAddress = "unix:///var/run/esgw/envoy-admin.sock"
	b, err := RenderBootstrap(opts)
	if err != nil {
		t.Fatal(err)
	}
	doc := parseBootstrapYAML(t, b)
	if got := dig(t, doc, "admin", "address", "pipe", "path"); got != "/var/run/esgw/envoy-admin.sock" {
		t.Fatalf("admin pipe path = %v:\n%s", got, b)
	}
}

func TestRenderBootstrapAdminTCP(t *testing.T) {
	b, err := RenderBootstrap(validOpts())
	if err != nil {
		t.Fatal(err)
	}
	doc := parseBootstrapYAML(t, b)
	sa := dig(t, doc, "admin", "address", "socket_address").(map[string]any)
	if sa["address"] != "127.0.0.1" || sa["port_value"] != 9901 {
		t.Fatalf("admin socket_address = %v:\n%s", sa, b)
	}
}

func TestRenderBootstrapDeterministic(t *testing.T) {
	first, err := RenderBootstrap(validOpts())
	if err != nil {
		t.Fatal(err)
	}
	second, err := RenderBootstrap(validOpts())
	if err != nil {
		t.Fatal(err)
	}
	if string(first) != string(second) {
		t.Fatal("RenderBootstrap is not deterministic: same opts produced different bytes")
	}
}

func TestRenderBootstrapInvalidAdminAddress(t *testing.T) {
	for _, addr := range []string{
		"",                     // 空
		"unix://",              // scheme 后无路径
		"tcp://127.0.0.1:9901", // 不支持的 scheme
		"127.0.0.1",            // 缺端口
		"127.0.0.1:0",          // 端口越界
		"127.0.0.1:70000",      // 端口越界
		"127.0.0.1:abc",        // 端口非数字
	} {
		opts := validOpts()
		opts.AdminAddress = addr
		if _, err := RenderBootstrap(opts); err == nil {
			t.Fatalf("adminAddress %q: want error", addr)
		}
	}
}

func TestRenderBootstrapInvalidXDSListen(t *testing.T) {
	for _, listen := range []string{
		"",                      // 空
		"127.0.0.1",             // 缺端口
		"127.0.0.1:0",           // 端口越界
		"127.0.0.1:70000",       // 端口越界
		"127.0.0.1:abc",         // 端口非数字
		":18000",                // 空 host
		"tcp://127.0.0.1:18000", // scheme 形态
	} {
		opts := validOpts()
		opts.XDSListen = listen
		if _, err := RenderBootstrap(opts); err == nil {
			t.Fatalf("xds listen %q: want error", listen)
		}
	}
}

func TestRenderBootstrapKeyFields(t *testing.T) {
	b, err := RenderBootstrap(validOpts())
	if err != nil {
		t.Fatal(err)
	}
	doc := parseBootstrapYAML(t, b)

	// dynamic_resources：ads_config GRPC/V3 指向 esgw_xds；cds/lds 走 ads。
	ads := dig(t, doc, "dynamic_resources", "ads_config").(map[string]any)
	if ads["api_type"] != "GRPC" || ads["transport_api_version"] != "V3" {
		t.Fatalf("ads_config = %v:\n%s", ads, b)
	}
	svcs := ads["grpc_services"].([]any)
	if len(svcs) != 1 {
		t.Fatalf("grpc_services = %v", svcs)
	}
	if got := svcs[0].(map[string]any)["envoy_grpc"].(map[string]any)["cluster_name"]; got != XDSClusterName {
		t.Fatalf("ads grpc cluster_name = %v, want %q", got, XDSClusterName)
	}
	for _, k := range []string{"cds_config", "lds_config"} {
		cs := dig(t, doc, "dynamic_resources", k).(map[string]any)
		if cs["resource_api_version"] != "V3" {
			t.Fatalf("%s = %v", k, cs)
		}
		if _, ok := cs["ads"]; !ok {
			t.Fatalf("%s missing ads: %v", k, cs)
		}
	}

	// static_resources.clusters[esgw_xds]：STATIC、显式 h2、load_assignment
	// 指向 XDSListen。
	clusters := dig(t, doc, "static_resources", "clusters").([]any)
	if len(clusters) != 1 {
		t.Fatalf("clusters = %v", clusters)
	}
	cl := clusters[0].(map[string]any)
	if cl["name"] != XDSClusterName || cl["type"] != "STATIC" {
		t.Fatalf("xds cluster = %v", cl)
	}
	if cl["connect_timeout"] != "5s" {
		t.Fatalf("xds cluster connect_timeout = %v", cl["connect_timeout"])
	}
	// lb_policy: ROUND_ROBIN 是枚举零值，protojson 省略（产物风格与
	// static.Render 一致：零值字段不输出）；缺省即 Envoy 默认 ROUND_ROBIN。
	if v, ok := cl["lb_policy"]; ok && v != "ROUND_ROBIN" {
		t.Fatalf("xds cluster lb_policy = %v, want ROUND_ROBIN (or omitted)", v)
	}
	hpo := cl["typed_extension_protocol_options"].(map[string]any)["envoy.extensions.upstreams.http.v3.HttpProtocolOptions"].(map[string]any)
	if _, ok := hpo["explicit_http_config"].(map[string]any)["http2_protocol_options"]; !ok {
		t.Fatalf("HttpProtocolOptions missing explicit h2: %v", hpo)
	}
	ep := dig(t, cl, "load_assignment", "endpoints").([]any)[0].(map[string]any)["lb_endpoints"].([]any)[0]
	sa := dig(t, ep.(map[string]any), "endpoint", "address", "socket_address").(map[string]any)
	if sa["address"] != "127.0.0.1" || sa["port_value"] != 18000 {
		t.Fatalf("esgw_xds endpoint = %v, want 127.0.0.1:18000", sa)
	}
}

// TestRenderBootstrapEnvoyValidate 用真实 envoy 二进制做 --mode validate
// （A7 单测层证据）。复用 envoycheck 的发现顺序；无二进制时按既有约定
// 降级 skip（同 compile.go runEnvoyCheck 的 Warning 降级语义）。
func TestRenderBootstrapEnvoyValidate(t *testing.T) {
	bin, err := envoycheck.FindBinary("")
	if err != nil {
		if errors.Is(err, envoycheck.ErrBinaryNotFound) {
			t.Skipf("envoy binary not found, skip --mode validate: %v", err)
		}
		t.Fatal(err)
	}
	b, err := RenderBootstrap(validOpts())
	if err != nil {
		t.Fatal(err)
	}
	if err := envoycheck.Validate(context.Background(), bin, b, 0); err != nil {
		t.Fatalf("envoy --mode validate rejected bootstrap:\n%v\n%s", err, b)
	}
}
