package xds

import (
	"bytes"
	"fmt"
	"net"
	"strconv"
	"strings"
	"time"

	bootstrapv3 "github.com/envoyproxy/go-control-plane/envoy/config/bootstrap/v3"
	clusterv3 "github.com/envoyproxy/go-control-plane/envoy/config/cluster/v3"
	corev3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	endpointv3 "github.com/envoyproxy/go-control-plane/envoy/config/endpoint/v3"
	upstreamhttpv3 "github.com/envoyproxy/go-control-plane/envoy/extensions/upstreams/http/v3"
	"google.golang.org/protobuf/types/known/anypb"
	"google.golang.org/protobuf/types/known/durationpb"

	"github.com/linkinghack/envoy-standalone-gateway/internal/deliver/static"
)

// XDSClusterName 是接入 bootstrap 中指向 esgw ADS 的 static cluster 名
// （下发层 §2.7 骨架固定名）。
const XDSClusterName = "esgw_xds"

// node 标识兜底默认值（下发层 §2.3），与 internal/config 的默认值保持一致：
// esgw bootstrap 命令经 config.LoadFile 填默认后传入非空值，这里的默认值
// 服务于以库形态直接调用 RenderBootstrap 的场景。
const (
	defaultNodeID      = "esgw-node"
	defaultNodeCluster = "esgw"
)

// xdsConnectTimeout 是 esgw_xds cluster 的 connect_timeout（§2.7 骨架 5s）。
const xdsConnectTimeout = 5 * time.Second

// BootstrapOpts 是接入 bootstrap 的渲染参数（technical_design §3 冻结签名）。
type BootstrapOpts struct {
	NodeID       string // node.id（默认 esgw-node）
	NodeCluster  string // node.cluster（默认 esgw）
	XDSListen    string // esgw ADS 地址（host:port；loopback 校验归 config 层，这里只做形态解析）
	AdminAddress string // unix:///<path> 或 host:port（SD5）
}

// RenderBootstrap 渲染接入 bootstrap（下发层 §2.7：xds 模式下 Envoy 唯一的
// static 文件；§5.7 仅下发模式由 esgw bootstrap 导出）。纯函数：无 IO、
// 不读时间/环境，同一 opts 两次调用字节级相同（确定性要求同 static.Render）。
//
// 产物骨架（§2.7）：node、admin（unix:/// → pipe；host:port →
// socket_address）、dynamic_resources（ads_config GRPC/V3 + cds/lds 走
// ads）、static_resources.clusters[esgw_xds]（STATIC、显式 h2、
// load_assignment 指向 XDSListen）。构建路径与 static.Render 一致：
// 构造 bootstrapv3.Bootstrap proto → PGV Validate 自检 → protojson→map→
// 确定性 YAML（static.MarshalYAML）。
//
// 文件头写 node_id 而不写 config_version：接入 bootstrap 与配置版本无关
// （config_version 是 static 产物/node.metadata 的生效确认标记，见
// static.Render 与 260717-4 §4.1）。
func RenderBootstrap(opts BootstrapOpts) ([]byte, error) {
	b, err := buildBootstrap(opts)
	if err != nil {
		return nil, err
	}
	// PGV 自检：产物不出管理面前先过 Envoy 约束校验（同 Compile 的 F 检查哲学）。
	if err := b.Validate(); err != nil {
		return nil, fmt.Errorf("bootstrap: PGV validate: %w", err)
	}
	body, err := static.MarshalYAML(b)
	if err != nil {
		return nil, fmt.Errorf("bootstrap: %w", err)
	}
	var buf bytes.Buffer
	buf.WriteString("# Generated by esgw. DO NOT EDIT.\n")
	buf.WriteString("# node_id: " + b.Node.GetId() + "\n")
	buf.Write(body)
	return buf.Bytes(), nil
}

// buildBootstrap 按 §2.7 骨架构造 bootstrapv3.Bootstrap proto。
func buildBootstrap(opts BootstrapOpts) (*bootstrapv3.Bootstrap, error) {
	nodeID := opts.NodeID
	if nodeID == "" {
		nodeID = defaultNodeID
	}
	nodeCluster := opts.NodeCluster
	if nodeCluster == "" {
		nodeCluster = defaultNodeCluster
	}
	admin, err := parseAdminAddress(opts.AdminAddress)
	if err != nil {
		return nil, fmt.Errorf("bootstrap: adminAddress: %w", err)
	}
	xdsAddr, err := parseSocketAddress(opts.XDSListen)
	if err != nil {
		return nil, fmt.Errorf("bootstrap: xds listen: %w", err)
	}

	// ADS 走 gRPC，esgw_xds cluster 必须显式开启 HTTP/2（§2.7 骨架）。
	h2, err := anypb.New(&upstreamhttpv3.HttpProtocolOptions{
		UpstreamProtocolOptions: &upstreamhttpv3.HttpProtocolOptions_ExplicitHttpConfig_{
			ExplicitHttpConfig: &upstreamhttpv3.HttpProtocolOptions_ExplicitHttpConfig{
				ProtocolConfig: &upstreamhttpv3.HttpProtocolOptions_ExplicitHttpConfig_Http2ProtocolOptions{
					Http2ProtocolOptions: &corev3.Http2ProtocolOptions{},
				},
			},
		},
	})
	if err != nil {
		return nil, fmt.Errorf("bootstrap: marshal HttpProtocolOptions: %w", err)
	}

	return &bootstrapv3.Bootstrap{
		Node:  &corev3.Node{Id: nodeID, Cluster: nodeCluster},
		Admin: &bootstrapv3.Admin{Address: admin},
		DynamicResources: &bootstrapv3.Bootstrap_DynamicResources{
			AdsConfig: &corev3.ApiConfigSource{
				ApiType:             corev3.ApiConfigSource_GRPC,
				TransportApiVersion: corev3.ApiVersion_V3,
				GrpcServices: []*corev3.GrpcService{{
					TargetSpecifier: &corev3.GrpcService_EnvoyGrpc_{
						EnvoyGrpc: &corev3.GrpcService_EnvoyGrpc{ClusterName: XDSClusterName},
					},
				}},
			},
			CdsConfig: adsConfigSource(),
			LdsConfig: adsConfigSource(),
		},
		StaticResources: &bootstrapv3.Bootstrap_StaticResources{
			Clusters: []*clusterv3.Cluster{{
				Name:                 XDSClusterName,
				ClusterDiscoveryType: &clusterv3.Cluster_Type{Type: clusterv3.Cluster_STATIC},
				ConnectTimeout:       durationpb.New(xdsConnectTimeout),
				LbPolicy:             clusterv3.Cluster_ROUND_ROBIN,
				TypedExtensionProtocolOptions: map[string]*anypb.Any{
					"envoy.extensions.upstreams.http.v3.HttpProtocolOptions": h2,
				},
				LoadAssignment: &endpointv3.ClusterLoadAssignment{
					ClusterName: XDSClusterName,
					Endpoints: []*endpointv3.LocalityLbEndpoints{{
						LbEndpoints: []*endpointv3.LbEndpoint{{
							HostIdentifier: &endpointv3.LbEndpoint_Endpoint{
								Endpoint: &endpointv3.Endpoint{Address: xdsAddr},
							},
						}},
					}},
				},
			}},
		},
	}, nil
}

// adsConfigSource 返回「走 ADS」的 ConfigSource（cds_config/lds_config 共用，
// resource_api_version V3，§2.7 骨架）。
func adsConfigSource() *corev3.ConfigSource {
	return &corev3.ConfigSource{
		ResourceApiVersion:    corev3.ApiVersion_V3,
		ConfigSourceSpecifier: &corev3.ConfigSource_Ads{Ads: &corev3.AggregatedConfigSource{}},
	}
}

// parseAdminAddress 解析 admin 地址（SD5 两种形态）：unix:///<path> → pipe，
// host:port → socket_address。形态规则与 config.validateAdminAddress 一致。
func parseAdminAddress(addr string) (*corev3.Address, error) {
	// "unix://" 是 scheme，其后必须是绝对路径（SD5：unix:///<path>）。
	if path, ok := strings.CutPrefix(addr, "unix:///"); ok {
		if path == "" {
			return nil, fmt.Errorf("%q has an empty socket path", addr)
		}
		return &corev3.Address{
			Address: &corev3.Address_Pipe{Pipe: &corev3.Pipe{Path: "/" + path}},
		}, nil
	}
	// 显式拒绝其他 scheme（否则 "tcp://127.0.0.1:9901" 会被 SplitHostPort
	// 拆出 host "tcp://127.0.0.1" 而漏过）。
	if strings.Contains(addr, "://") {
		return nil, fmt.Errorf("%q invalid (want unix:///<path> or host:port)", addr)
	}
	return parseSocketAddress(addr)
}

// parseSocketAddress 把 host:port 解析为 socket_address。仅形态解析：
// loopback 安全校验归 config 层（config.validateListen）。
func parseSocketAddress(addr string) (*corev3.Address, error) {
	host, port, err := net.SplitHostPort(addr)
	if err != nil {
		return nil, fmt.Errorf("%q invalid (want host:port)", addr)
	}
	if host == "" {
		return nil, fmt.Errorf("%q has an empty host", addr)
	}
	p, err := strconv.Atoi(port)
	if err != nil || p < 1 || p > 65535 {
		return nil, fmt.Errorf("invalid port %q (want 1-65535)", port)
	}
	return &corev3.Address{
		Address: &corev3.Address_SocketAddress{SocketAddress: &corev3.SocketAddress{
			Address:       host,
			PortSpecifier: &corev3.SocketAddress_PortValue{PortValue: uint32(p)},
		}},
	}, nil
}
