/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthBootstrap"];
        put?: never;
        post: operations["createAuthBootstrap"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuthMethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConfigDraft"];
        put: operations["replaceConfigDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConfigObjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/objects/{kind}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["KindPath"];
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        get: operations["getConfigObject"];
        put: operations["putConfigObject"];
        post?: never;
        delete: operations["deleteConfigObject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConfigSchemas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/compiled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCompiledConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/draft/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDraftDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConfigStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConfigVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/versions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VersionPath"];
            };
            cookie?: never;
        };
        get: operations["getConfigVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/versions/{id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VersionPath"];
            };
            cookie?: never;
        };
        get: operations["getConfigVersionSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/versions/{id}/compiled": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VersionPath"];
            };
            cookie?: never;
        };
        get: operations["getConfigVersionCompiled"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/versions/{id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VersionPath"];
            };
            cookie?: never;
        };
        get: operations["getConfigVersionDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/versions/{id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VersionPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rollbackConfigVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStatusSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/listeners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStatusListeners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStatusClusters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/clusters/{name}/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStatusClusterEndpoints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStatusRoutes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/certs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStatusCerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStatsOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStatsSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCertificates"];
        put?: never;
        post: operations["createCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certs/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        get: operations["getCertificate"];
        put?: never;
        post?: never;
        delete: operations["deleteCertificate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSystemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/envoy/stats/prometheus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEnvoyPrometheusStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getManagementMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @enum {string} */
                code: "INVALID_ARGUMENT" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "NO_CHANGES" | "VALIDATION_FAILED" | "RATE_LIMITED" | "INTERNAL" | "BAD_GATEWAY";
                message: string;
                details?: components["schemas"]["Diagnostic"][];
            };
        };
        Diagnostic: {
            stage: string;
            source?: {
                [key: string]: unknown;
            };
            message: string;
            /** @enum {string} */
            severity: "error" | "warning";
        };
        Credentials: {
            username: string;
            /** Format: password */
            password: string;
        };
        BootstrapState: {
            required: boolean;
            /** Format: date-time */
            expiresAt: string | null;
        };
        Session: {
            user: {
                name: string;
                roles: "admin"[];
            };
            /** Format: date-time */
            expiresAt: string;
        };
        DraftFile: {
            path: string;
            content: string;
        };
        Draft: {
            /** @enum {string} */
            sourceType: "protocol" | "native";
            resourceVersion: string;
            /** Format: date-time */
            updatedAt?: string | null;
            files: components["schemas"]["DraftFile"][];
        };
        ReplaceDraftRequest: {
            /** @enum {string} */
            sourceType: "protocol" | "native";
            expectedResourceVersion?: string;
            files: components["schemas"]["DraftFile"][];
        };
        DraftMutation: {
            draftResourceVersion: string;
            object?: components["schemas"]["ConfigObject"];
        };
        /** @enum {string} */
        ConfigKind: "Gateway" | "Listener" | "Route" | "Upstream" | "Policy" | "EnvoyResources";
        ConfigObject: {
            /** @enum {string} */
            apiVersion: "esgw/v1alpha1";
            kind: components["schemas"]["ConfigKind"];
            metadata: {
                name: string;
            } & {
                [key: string]: unknown;
            };
            spec: {
                [key: string]: unknown;
            };
        };
        ObjectList: {
            items: components["schemas"]["ConfigObject"][];
            total: number;
            resourceVersion: string;
        };
        ValidationResult: {
            ok: boolean;
            /** @enum {string} */
            mode: "xds" | "static";
            irVersion?: string | null;
            results: components["schemas"]["Diagnostic"][];
        };
        PublishResult: {
            version: components["schemas"]["Version"];
            delivery: {
                /** @enum {string} */
                mode: "xds" | "static";
                state: string;
            };
        };
        Version: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            createdAt: string;
            author: string;
            message: string;
            mode: string;
            irVersion: string;
            state: string;
            /** Format: int64 */
            parentId?: number;
            /** Format: int64 */
            rollbackOf?: number;
        };
        Certificate: {
            name: string;
            subject?: string;
            sans: string[];
            /** Format: date-time */
            notAfter?: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description Public certificate chain only */
            certificatePem: string;
            references: string[];
        };
        CreateCertificateRequest: {
            name: string;
            certificatePem: string;
            /** Format: password */
            privateKeyPem: string;
        };
    };
    responses: {
        /** @description Authenticated session */
        Session: {
            headers: {
                "Set-Cookie"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Session"];
            };
        };
        /** @description Draft mutation result */
        DraftMutation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DraftMutation"];
            };
        };
        /** @description Normalized bounded state payload */
        StatePayload: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Process probe */
        Probe: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    status: string;
                };
            };
        };
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Invalid request */
        Error400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication required */
        Error401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        Error404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource conflict */
        Error409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Configuration validation failed */
        Error422: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Login rate limited */
        Error429: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Envoy admin unavailable */
        Error502: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        CsrfHeader: "1";
        ExpectedResourceVersion: string;
        KindQuery: components["schemas"]["ConfigKind"];
        KindPath: components["schemas"]["ConfigKind"];
        NamePath: string;
        VersionPath: number;
        ModeQuery: "xds" | "static";
        Limit: number;
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAuthBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bootstrap state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapState"];
                };
            };
        };
    };
    createAuthBootstrap: {
        parameters: {
            query?: never;
            header: {
                "X-ESGW-Request": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            201: components["responses"]["Session"];
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header: {
                "X-ESGW-Request": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            200: components["responses"]["Session"];
            401: components["responses"]["Unauthenticated"];
            429: components["responses"]["RateLimited"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-ESGW-Request": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session destroyed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getAuthSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Session"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header: {
                "X-ESGW-Request": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: password */
                    oldPassword: string;
                    /** Format: password */
                    newPassword: string;
                };
            };
        };
        responses: {
            /** @description Password changed and other sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    listAuthMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available authentication methods */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            /** @enum {string} */
                            type: "local";
                        }[];
                    };
                };
            };
        };
    };
    getConfigDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current filesystem draft */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
        };
    };
    replaceConfigDraft: {
        parameters: {
            query?: never;
            header: {
                "X-ESGW-Request": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceDraftRequest"];
            };
        };
        responses: {
            200: components["responses"]["DraftMutation"];
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    listConfigObjects: {
        parameters: {
            query?: {
                kind?: components["parameters"]["KindQuery"];
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft objects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectList"];
                };
            };
        };
    };
    getConfigObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["KindPath"];
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One protocol object */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigObject"];
                    "application/yaml": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    putConfigObject: {
        parameters: {
            query?: {
                expectedResourceVersion?: components["parameters"]["ExpectedResourceVersion"];
            };
            header: {
                "X-ESGW-Request": components["parameters"]["CsrfHeader"];
            };
            path: {
                kind: components["parameters"]["KindPath"];
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigObject"];
                "application/yaml": string;
            };
        };
        responses: {
            200: components["responses"]["DraftMutation"];
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteConfigObject: {
        parameters: {
            query?: {
                expectedResourceVersion?: components["parameters"]["ExpectedResourceVersion"];
            };
            header: {
                "X-ESGW-Request": components["parameters"]["CsrfHeader"];
            };
            path: {
                kind: components["parameters"]["KindPath"];
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DraftMutation"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getConfigSchemas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Protocol JSON Schema bundle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/schema+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    validateConfig: {
        parameters: {
            query?: {
                mode?: components["parameters"]["ModeQuery"];
            };
            header: {
                "X-ESGW-Request": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default false */
                    envoyValidate?: boolean;
                };
            };
        };
        responses: {
            /** @description Validation result; invalid configuration is represented by ok=false */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getCompiledConfig: {
        parameters: {
            query?: {
                mode?: components["parameters"]["ModeQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deterministic compiled artifact */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    getDraftDiff: {
        parameters: {
            query?: {
                against?: string;
                format?: "unified" | "summary";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Text or object summary diff */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    publishConfig: {
        parameters: {
            query?: never;
            header: {
                "X-ESGW-Request": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    message: string;
                    expectedResourceVersion?: string;
                };
            };
        };
        responses: {
            /** @description Publish accepted and awaiting confirmation */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishResult"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getConfigStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published/effective status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listConfigVersions: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable versions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Version"][];
                        total: number;
                    };
                };
            };
        };
    };
    getConfigVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VersionPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getConfigVersionSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["VersionPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version source files */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getConfigVersionCompiled: {
        parameters: {
            query?: {
                mode?: components["parameters"]["ModeQuery"];
                format?: "json" | "static-yaml";
            };
            header?: never;
            path: {
                id: components["parameters"]["VersionPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compiled version artifact */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/yaml": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getConfigVersionDiff: {
        parameters: {
            query: {
                against: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["VersionPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version source diff */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    rollbackConfigVersion: {
        parameters: {
            query?: never;
            header: {
                "X-ESGW-Request": components["parameters"]["CsrfHeader"];
            };
            path: {
                id: components["parameters"]["VersionPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default false */
                    publish?: boolean;
                    /** @default false */
                    force?: boolean;
                };
            };
        };
        responses: {
            200: components["responses"]["DraftMutation"];
            /** @description Rollback publish accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishResult"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getStatusSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["StatePayload"];
        };
    };
    listStatusListeners: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["StatePayload"];
        };
    };
    listStatusClusters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["StatePayload"];
        };
    };
    listStatusClusterEndpoints: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["StatePayload"];
            404: components["responses"]["NotFound"];
        };
    };
    listStatusRoutes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["StatePayload"];
        };
    };
    listStatusCerts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["StatePayload"];
        };
    };
    getStatsOverview: {
        parameters: {
            query?: {
                window?: "5m" | "15m" | "1h" | "6h";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["StatePayload"];
        };
    };
    listStatsSeries: {
        parameters: {
            query?: {
                dimension?: "route" | "cluster";
                name?: string;
                metric?: string;
                window?: "5m" | "15m" | "1h" | "6h";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["StatePayload"];
        };
    };
    listCertificates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Managed certificate metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Certificate"][];
                        total: number;
                    };
                };
            };
        };
    };
    createCertificate: {
        parameters: {
            query?: never;
            header: {
                "X-ESGW-Request": components["parameters"]["CsrfHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCertificateRequest"];
            };
        };
        responses: {
            /** @description Managed certificate metadata; private key is never returned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Certificate"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    getCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Certificate metadata and public chain */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Certificate"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteCertificate: {
        parameters: {
            query?: never;
            header: {
                "X-ESGW-Request": components["parameters"]["CsrfHeader"];
            };
            path: {
                name: components["parameters"]["NamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Certificate deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getSystemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build, topology and Envoy information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getEnvoyPrometheusStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw Envoy Prometheus exposition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            502: components["responses"]["BadGateway"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Probe"];
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Probe"];
            503: components["responses"]["Probe"];
        };
    };
    getManagementMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description esgw management-plane Prometheus exposition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
