apiVersion: esgw/v1alpha1
kind: Listener
metadata: {name: tcp}
spec:
  port: 9000
  protocol: TCP
  policies:
    - rateLimit: {requests: 10, unit: second}
---
apiVersion: esgw/v1alpha1
kind: Route
metadata: {name: tcp}
spec:
  listeners: [tcp]
  forward: {upstream: app}
---
apiVersion: esgw/v1alpha1
kind: Upstream
metadata: {name: app}
spec:
  endpoints: [{address: 127.0.0.1, port: 9001}]
