package static

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	bootstrapv3 "github.com/envoyproxy/go-control-plane/envoy/config/bootstrap/v3"
	corev3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/structpb"
	yamlv3 "gopkg.in/yaml.v3"

	"github.com/linkinghack/envoy-standalone-gateway/internal/ir"
)

// DefaultAdminSocketPath 是 M0 static 产物的 admin 地址（uds，RK5 落地：
// unix socket 文件权限即访问控制，无端口暴露）。渲染期覆盖 T5 Bootstrap
// 骨架的 127.0.0.1:9901 占位（下发层 §4.1：渲染期可覆盖/补齐 admin 段）。
// 运行期数据目录形态（/var/run/esgw/envoy-admin.sock）归 S7 M-PROC 托管落盘。
const DefaultAdminSocketPath = "/tmp/esgw-admin.sock"

// ConfigVersionMetadataKey 是渲染期注入 node.metadata 的版本标记键
// （260717-4 §4.1 契约：M-STATE 从 /config_dump bootstrap 段读取，
// 是 static 模式生效确认的唯一机器可读依据）。
const ConfigVersionMetadataKey = "esgw.config_version"

// Render 把 IR 渲染为单文件 envoy.yaml（下发层 §4.1；technical_design §3
// 冻结签名）。纯函数：无 IO、不读时间/环境，同一 IR 两次调用字节级相同（SD6）。
//
// 渲染期两条版本标记：
//  1. 文件头注释 config_version（人读，git diff 友好）；
//  2. node.metadata 注入 esgw.config_version: <IR.Version>——注入发生在
//     IR.Bootstrap 的深拷贝上，不回改 IR、不参与 IR.Version 哈希（循环依赖）。
//
// admin 段固定为 M0 默认 uds（DefaultAdminSocketPath），覆盖 Bootstrap 骨架占位。
//
// 产物形态：static_resources 只含 listeners/clusters/secrets（Bootstrap 的
// StaticResources 无 route/endpoint 字段——F5 已把编译产物的 route_config 内联
// 进 HCM、端点内联进 Cluster；static 模式下残留的 IR.Routes/IR.Endpoints 只能是
// EnvoyResources 引入的引用形态资源，在 static bootstrap 中无处安放，不输出，
// 见 T6 进展记录）。
func Render(i *ir.IR) ([]byte, error) {
	return RenderWithOptions(i, RenderOptions{})
}

// RenderOptions customizes runtime-only bootstrap fields without mutating IR.
type RenderOptions struct {
	AdminSocketPath string
}

// RenderWithOptions renders static YAML with an explicit runtime admin socket.
func RenderWithOptions(i *ir.IR, options RenderOptions) ([]byte, error) {
	if i == nil {
		return nil, fmt.Errorf("render: nil IR")
	}
	if options.AdminSocketPath == "" {
		options.AdminSocketPath = DefaultAdminSocketPath
	}
	b := renderBootstrap(i, options)
	body, err := MarshalYAML(b)
	if err != nil {
		return nil, fmt.Errorf("render: %w", err)
	}
	var buf bytes.Buffer
	buf.WriteString("# Generated by esgw. DO NOT EDIT.\n")
	buf.WriteString("# config_version: " + i.Version + "\n")
	buf.Write(body)
	return buf.Bytes(), nil
}

// MarshalYAML 把 proto 消息渲染为确定性 YAML 文档正文（protojson→map→
// 确定性 YAML 发射器）：map 键字典序，标量/键的引用风格由 yaml.v3 对单值
// Marshal 的结果决定。不含文件头注释（由调用方按产物类型书写）。
// static.Render 与 xds 接入 bootstrap（Sprint 260720 T4）共用本路径，
// 保证两类产物风格一致。
func MarshalYAML(m proto.Message) ([]byte, error) {
	mm, err := protoToMap(m)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	emitMap(&buf, mm, 0)
	return buf.Bytes(), nil
}

// renderBootstrap 深拷贝 IR.Bootstrap 并施加渲染期改写：注入版本 metadata、
// 覆盖 admin 为 uds、装配 static_resources。IR 本体不变（260717-4 §4.1）。
func renderBootstrap(i *ir.IR, options RenderOptions) *bootstrapv3.Bootstrap {
	var b *bootstrapv3.Bootstrap
	if i.Bootstrap != nil {
		b = proto.Clone(i.Bootstrap).(*bootstrapv3.Bootstrap)
	} else {
		b = &bootstrapv3.Bootstrap{}
	}
	if b.Node == nil {
		b.Node = &corev3.Node{}
	}
	md := b.Node.GetMetadata()
	if md == nil {
		md = &structpb.Struct{Fields: map[string]*structpb.Value{}}
		b.Node.Metadata = md
	}
	md.Fields[ConfigVersionMetadataKey] = structpb.NewStringValue(i.Version)
	b.Admin = &bootstrapv3.Admin{
		Address: &corev3.Address{
			Address: &corev3.Address_Pipe{Pipe: &corev3.Pipe{Path: options.AdminSocketPath}},
		},
	}
	b.StaticResources = &bootstrapv3.Bootstrap_StaticResources{
		Listeners: sortedByName(i.Listeners),
		Clusters:  sortedByName(i.Clusters),
		Secrets:   sortedByName(i.Secrets),
	}
	return b
}

// sortedByName 返回资源 map 按 name 排序后的切片（map 输出按 name 排序，
// 编译层 §5 确定性规约）。
func sortedByName[M interface {
	proto.Message
	GetName() string
}](m map[string]M) []M {
	names := make([]string, 0, len(m))
	for n := range m {
		names = append(names, n)
	}
	sort.Strings(names)
	out := make([]M, 0, len(names))
	for _, n := range names {
		out = append(out, m[n])
	}
	return out
}

// protoToMap 把 proto 消息经 protojson（UseProtoNames，与 Envoy YAML 文档的
// snake_case 字段名一致）转为 map[string]any，供确定性 YAML/JSON 输出。
func protoToMap(m proto.Message) (map[string]any, error) {
	b, err := protojson.MarshalOptions{UseProtoNames: true}.Marshal(m)
	if err != nil {
		return nil, err
	}
	var v map[string]any
	if err := json.Unmarshal(b, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// 以下为确定性 YAML 发射器：map 键一律字典序（SD6），标量/键的引用风格
// 交给 yaml.v3 对单值 Marshal 的结果决定（如 "@type"、YAML 1.1 布尔词
// "on"/"yes"、数字形态字符串都会被正确加引号）。

const indentStep = 2

// emitMap 把 map 以 level 级缩进输出为 YAML mapping（键排序）。
func emitMap(buf *bytes.Buffer, m map[string]any, level int) {
	emitKeys(buf, m, sortedKeys(m), level)
}

// emitKeys 按给定键序输出 mapping 条目。
func emitKeys(buf *bytes.Buffer, m map[string]any, keys []string, level int) {
	pad := strings.Repeat(" ", level*indentStep)
	for _, k := range keys {
		buf.WriteString(pad)
		buf.WriteString(scalar(k))
		buf.WriteByte(':')
		emitValue(buf, m[k], level)
	}
}

// emitValue 在 "key:" 或 "-" 之后输出一个值：标量内联，复合值换行缩进。
// level 是 key/dash 所在层级；子节点缩进 level+1。
func emitValue(buf *bytes.Buffer, v any, level int) {
	switch t := v.(type) {
	case map[string]any:
		if len(t) == 0 {
			buf.WriteString(" {}\n")
			return
		}
		buf.WriteByte('\n')
		emitMap(buf, t, level+1)
	case []any:
		if len(t) == 0 {
			buf.WriteString(" []\n")
			return
		}
		buf.WriteByte('\n')
		emitList(buf, t, level+1)
	default:
		buf.WriteByte(' ')
		buf.WriteString(scalar(t))
		buf.WriteByte('\n')
	}
}

// emitList 把列表以 level 级缩进输出为 YAML sequence。
func emitList(buf *bytes.Buffer, l []any, level int) {
	pad := strings.Repeat(" ", level*indentStep)
	for _, item := range l {
		buf.WriteString(pad)
		buf.WriteByte('-')
		switch t := item.(type) {
		case map[string]any:
			if len(t) == 0 {
				buf.WriteString(" {}\n")
				continue
			}
			// 首键与 dash 同行（标准 Envoy YAML 风格），其余键缩进一级。
			keys := sortedKeys(t)
			buf.WriteByte(' ')
			buf.WriteString(scalar(keys[0]))
			buf.WriteByte(':')
			emitValue(buf, t[keys[0]], level+1)
			emitKeys(buf, t, keys[1:], level+1)
		case []any:
			if len(t) == 0 {
				buf.WriteString(" []\n")
				continue
			}
			buf.WriteByte('\n')
			emitList(buf, t, level+1)
		default:
			buf.WriteByte(' ')
			buf.WriteString(scalar(t))
			buf.WriteByte('\n')
		}
	}
}

// scalar 用 yaml.v3 对单值 Marshal 取得正确的引用风格（去掉结尾换行）。
// json.Unmarshal 的数字为 float64，yaml.v3 输出整数值不带小数点。
func scalar(v any) string {
	b, err := yamlv3.Marshal(v)
	if err != nil {
		return fmt.Sprintf("%v", v)
	}
	return strings.TrimRight(string(b), "\n")
}

// sortedKeys 返回 map 键的字典序副本。
func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
