package static_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	yamlv3 "gopkg.in/yaml.v3"

	"github.com/linkinghack/envoy-standalone-gateway/internal/compile"
	"github.com/linkinghack/envoy-standalone-gateway/internal/deliver"
	"github.com/linkinghack/envoy-standalone-gateway/internal/deliver/static"
	"github.com/linkinghack/envoy-standalone-gateway/internal/ir"
	"github.com/linkinghack/envoy-standalone-gateway/internal/protocol"
)

// minimalConfig 是一份不依赖证书文件的最小合法配置（HTTP Listener + Route +
// Upstream），供渲染测试走 LoadDir → Compile 全链路构造真实 IR。
const minimalConfig = `
apiVersion: esgw/v1alpha1
kind: Listener
metadata: {name: http}
spec: {port: 80, protocol: HTTP}
---
apiVersion: esgw/v1alpha1
kind: Route
metadata: {name: web}
spec:
  listeners: [http]
  hostnames: [www.example.com]
  rules:
    - match: {path: {prefix: /}}
      backends: [{upstream: app}]
---
apiVersion: esgw/v1alpha1
kind: Upstream
metadata: {name: app}
spec:
  endpoints: [{address: 127.0.0.1, port: 8080}]
`

// compileMinimal 把最小配置编译为指定模式的 IR。
func compileMinimal(t *testing.T, mode compile.Mode) *ir.IR {
	t.Helper()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "config.yaml"), []byte(minimalConfig), 0o600); err != nil {
		t.Fatal(err)
	}
	cs, loadErrs := protocol.LoadDir(dir)
	if len(loadErrs) != 0 {
		t.Fatalf("load errors: %v", loadErrs)
	}
	out, cerrs := compile.Compile(cs, compile.Options{Mode: mode})
	for _, e := range cerrs {
		if e.Severity == compile.SeverityError {
			t.Fatalf("compile errors: %v", cerrs)
		}
	}
	if out == nil {
		t.Fatal("nil IR")
	}
	return out
}

// parseYAML 把产物解析回 map 供断言（也顺带验证产物是合法 YAML）。
func parseYAML(t *testing.T, b []byte) map[string]any {
	t.Helper()
	var v map[string]any
	if err := yamlv3.Unmarshal(b, &v); err != nil {
		t.Fatalf("rendered output is not valid YAML: %v\n%s", err, b)
	}
	return v
}

func TestRenderDeterministic(t *testing.T) {
	out := compileMinimal(t, compile.ModeStatic)
	first, err := static.Render(out)
	if err != nil {
		t.Fatal(err)
	}
	second, err := static.Render(out)
	if err != nil {
		t.Fatal(err)
	}
	if string(first) != string(second) {
		t.Fatal("Render is not deterministic: same IR produced different bytes")
	}
}

func TestRenderVersionMarkers(t *testing.T) {
	out := compileMinimal(t, compile.ModeStatic)
	b, err := static.Render(out)
	if err != nil {
		t.Fatal(err)
	}
	// 人读标记：文件头注释（下发层 §4.1）。
	if !strings.HasPrefix(string(b), "# Generated by esgw. DO NOT EDIT.\n# config_version: "+out.Version+"\n") {
		t.Fatalf("missing header comments:\n%s", b)
	}
	// 机器可读标记：node.metadata 注入 esgw.config_version（260717-4 §4.1）。
	doc := parseYAML(t, b)
	node, ok := doc["node"].(map[string]any)
	if !ok {
		t.Fatalf("no node section:\n%s", b)
	}
	md, ok := node["metadata"].(map[string]any)
	if !ok {
		t.Fatalf("no node.metadata:\n%s", b)
	}
	if md[static.ConfigVersionMetadataKey] != out.Version {
		t.Fatalf("node.metadata[%q] = %v, want %q", static.ConfigVersionMetadataKey, md[static.ConfigVersionMetadataKey], out.Version)
	}
}

func TestRenderDoesNotMutateIR(t *testing.T) {
	out := compileMinimal(t, compile.ModeStatic)
	if out.Bootstrap.GetNode().GetMetadata() != nil {
		t.Fatal("precondition: IR bootstrap node metadata should be nil")
	}
	if _, err := static.Render(out); err != nil {
		t.Fatal(err)
	}
	if out.Bootstrap.GetNode().GetMetadata() != nil {
		t.Fatal("Render mutated IR.Bootstrap (version injection must not write back)")
	}
	if out.Bootstrap.GetAdmin().GetAddress().GetPipe() != nil {
		t.Fatal("Render mutated IR.Bootstrap admin address")
	}
}

func TestRenderAdminUDS(t *testing.T) {
	out := compileMinimal(t, compile.ModeStatic)
	b, err := static.Render(out)
	if err != nil {
		t.Fatal(err)
	}
	doc := parseYAML(t, b)
	admin, ok := doc["admin"].(map[string]any)
	if !ok {
		t.Fatalf("no admin section:\n%s", b)
	}
	addr, ok := admin["address"].(map[string]any)
	if !ok {
		t.Fatalf("no admin.address:\n%s", b)
	}
	pipe, ok := addr["pipe"].(map[string]any)
	if !ok || pipe["path"] != static.DefaultAdminSocketPath {
		t.Fatalf("admin address is not the default uds %q:\n%s", static.DefaultAdminSocketPath, b)
	}
}

func TestRenderStaticResources(t *testing.T) {
	out := compileMinimal(t, compile.ModeStatic)
	b, err := static.Render(out)
	if err != nil {
		t.Fatal(err)
	}
	doc := parseYAML(t, b)
	sr, ok := doc["static_resources"].(map[string]any)
	if !ok {
		t.Fatalf("no static_resources:\n%s", b)
	}
	listeners, ok := sr["listeners"].([]any)
	if !ok || len(listeners) != 1 {
		t.Fatalf("want 1 listener:\n%s", b)
	}
	lis := listeners[0].(map[string]any)
	if lis["name"] != "lis/http" {
		t.Fatalf("listener name = %v, want lis/http", lis["name"])
	}
	clusters, ok := sr["clusters"].([]any)
	if !ok || len(clusters) != 1 {
		t.Fatalf("want 1 cluster:\n%s", b)
	}
	cl := clusters[0].(map[string]any)
	if cl["name"] != "us/app" {
		t.Fatalf("cluster name = %v, want us/app", cl["name"])
	}
	// static 形态：route_config 内联进 HCM，产物不应有独立 route 段之外的
	// RDS 引用——内联 route_config 出现在 listener typed_config 深处，
	// 此处只粗粒度确认产物包含内联的路由内容。
	if !strings.Contains(string(b), "route_config:") {
		t.Fatalf("expected inlined route_config in HCM:\n%s", b)
	}
}

func TestRenderNilIR(t *testing.T) {
	if _, err := static.Render(nil); err == nil {
		t.Fatal("expected error for nil IR")
	}
}

func TestSnapshotJSON(t *testing.T) {
	out := compileMinimal(t, compile.ModeXDS)
	first, err := deliver.SnapshotJSON(out)
	if err != nil {
		t.Fatal(err)
	}
	second, err := deliver.SnapshotJSON(out)
	if err != nil {
		t.Fatal(err)
	}
	if string(first) != string(second) {
		t.Fatal("SnapshotJSON is not deterministic")
	}
	var doc map[string]any
	if err := yamlv3.Unmarshal(first, &doc); err != nil { // JSON ⊂ YAML
		t.Fatalf("invalid JSON: %v", err)
	}
	for _, section := range []string{"version", "listeners", "clusters", "routes", "endpoints", "secrets"} {
		if _, ok := doc[section]; !ok {
			t.Fatalf("missing section %q:\n%s", section, first)
		}
	}
	if doc["version"] != out.Version {
		t.Fatalf("version = %v, want %q", doc["version"], out.Version)
	}
	listeners := doc["listeners"].(map[string]any)
	if _, ok := listeners["lis/http"]; !ok {
		t.Fatalf("missing listener lis/http:\n%s", first)
	}
	// xds 形态：STATIC cluster 的 CLA 抽到 endpoints 段。
	endpoints := doc["endpoints"].(map[string]any)
	if _, ok := endpoints["us/app"]; !ok {
		t.Fatalf("missing EDS resource us/app:\n%s", first)
	}
}
