package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// 合法的最小 esgw.yaml（xds 默认即可渲染接入 bootstrap）。
const okESGWYAML = "deliver:\n  xds:\n    listen: 127.0.0.1:18000\n    adminAddress: 127.0.0.1:9901\n"

// writeESGWYAML 在临时目录写一份 esgw.yaml，返回路径。
func writeESGWYAML(t *testing.T, content string) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), "esgw.yaml")
	if err := os.WriteFile(p, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	return p
}

// TestBootstrapUsageError 覆盖用法错误（exit 2）：-c 必填、--mode 仅接受
// xds（static 无接入 bootstrap 概念）、不接受位置参数。
func TestBootstrapUsageError(t *testing.T) {
	if code, _, _ := runCLI(t, "bootstrap"); code != 2 {
		t.Fatalf("missing -c: exit = %d, want 2", code)
	}
	cfg := writeESGWYAML(t, okESGWYAML)
	if code, _, _ := runCLI(t, "bootstrap", "-c", cfg, "--mode", "static"); code != 2 {
		t.Fatalf("--mode static: exit = %d, want 2", code)
	}
	if code, _, _ := runCLI(t, "bootstrap", "-c", cfg, "--mode", "bogus"); code != 2 {
		t.Fatalf("--mode bogus: exit = %d, want 2", code)
	}
	if code, _, _ := runCLI(t, "bootstrap", "-c", cfg, "extra"); code != 2 {
		t.Fatalf("positional arg: exit = %d, want 2", code)
	}
}

// TestBootstrapMissingConfig 覆盖 esgw.yaml 缺失/非法：exit 1。
func TestBootstrapMissingConfig(t *testing.T) {
	code, _, stderr := runCLI(t, "bootstrap", "-c", filepath.Join(t.TempDir(), "nonexistent.yaml"))
	if code != 1 {
		t.Fatalf("exit = %d, want 1; stderr:\n%s", code, stderr)
	}
	if !strings.Contains(stderr, "error: load esgw.yaml:") {
		t.Fatalf("missing load error line:\n%s", stderr)
	}
}

// TestBootstrapToFile 覆盖成功路径：产物写文件，含文件头与关键段。
func TestBootstrapToFile(t *testing.T) {
	cfg := writeESGWYAML(t, okESGWYAML)
	out := filepath.Join(t.TempDir(), "bootstrap.yaml")
	code, _, stderr := runCLI(t, "bootstrap", "-c", cfg, "-o", out)
	if code != 0 {
		t.Fatalf("exit = %d, stderr:\n%s", code, stderr)
	}
	b, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(b), "# Generated by esgw. DO NOT EDIT.\n# node_id: esgw-node\n") {
		t.Fatalf("missing header comments:\n%s", b)
	}
	for _, section := range []string{"dynamic_resources:", "static_resources:", "esgw_xds"} {
		if !strings.Contains(string(b), section) {
			t.Fatalf("missing %q:\n%s", section, b)
		}
	}
	// tcp admin 形态应渲染为 socket_address。
	if !strings.Contains(string(b), "socket_address:") {
		t.Fatalf("missing tcp admin socket_address:\n%s", b)
	}
}

// TestBootstrapStdoutDefault 覆盖输出契约：-o 缺省写 stdout（同 compile）。
func TestBootstrapStdoutDefault(t *testing.T) {
	cfg := writeESGWYAML(t, okESGWYAML)
	code, stdout, stderr := runCLI(t, "bootstrap", "-c", cfg)
	if code != 0 {
		t.Fatalf("exit = %d, stderr:\n%s", code, stderr)
	}
	if !strings.Contains(stdout, "dynamic_resources:") {
		t.Fatalf("artifact not written to stdout:\n%s", stdout)
	}
}

// TestUsageListsBootstrap 确认顶层 usage 已收录 bootstrap。
func TestUsageListsBootstrap(t *testing.T) {
	code, _, stderr := runCLI(t)
	if code != 2 {
		t.Fatalf("no args: exit = %d, want 2", code)
	}
	if !strings.Contains(stderr, "bootstrap") {
		t.Fatalf("usage missing bootstrap:\n%s", stderr)
	}
}
