package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/linkinghack/envoy-standalone-gateway/internal/compile/envoycheck"
)

// runCLI 以内存 buffer 跑 esgw 命令，返回退出码与捕获的 stdout/stderr。
func runCLI(t *testing.T, args ...string) (int, string, string) {
	t.Helper()
	var stdout, stderr bytes.Buffer
	code := run(args, &stdout, &stderr)
	return code, stdout.String(), stderr.String()
}

func TestCompileStaticToFile(t *testing.T) {
	out := filepath.Join(t.TempDir(), "envoy.yaml")
	code, _, stderr := runCLI(t, "compile", "-f", "testdata/ok", "--mode", "static", "-o", out)
	if code != 0 {
		t.Fatalf("exit = %d, stderr:\n%s", code, stderr)
	}
	b, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(b), "# Generated by esgw. DO NOT EDIT.\n# config_version: ") {
		t.Fatalf("missing header comments:\n%s", b)
	}
	if !strings.Contains(string(b), "esgw.config_version") {
		t.Fatalf("missing node.metadata version injection:\n%s", b)
	}
	if !strings.Contains(string(b), "lis/http") || !strings.Contains(string(b), "us/app") {
		t.Fatalf("missing resources:\n%s", b)
	}
}

func TestCompileXDS(t *testing.T) {
	out := filepath.Join(t.TempDir(), "snapshot.json")
	code, _, stderr := runCLI(t, "compile", "-f", "testdata/ok", "--mode", "xds", "-o", out)
	if code != 0 {
		t.Fatalf("exit = %d, stderr:\n%s", code, stderr)
	}
	b, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	var doc map[string]any
	if err := json.Unmarshal(b, &doc); err != nil {
		t.Fatalf("invalid JSON: %v\n%s", err, b)
	}
	for _, section := range []string{"version", "listeners", "clusters", "routes", "endpoints", "secrets"} {
		if _, ok := doc[section]; !ok {
			t.Fatalf("missing section %q:\n%s", section, b)
		}
	}
}

func TestCompileStdoutDefault(t *testing.T) {
	code, stdout, stderr := runCLI(t, "compile", "-f", "testdata/ok")
	if code != 0 {
		t.Fatalf("exit = %d, stderr:\n%s", code, stderr)
	}
	if !strings.Contains(stdout, "static_resources:") {
		t.Fatalf("artifact not written to stdout:\n%s", stdout)
	}
}

func TestLoadErrorFormat(t *testing.T) {
	code, _, stderr := runCLI(t, "compile", "-f", "testdata/err-load", "-o", filepath.Join(t.TempDir(), "x.yaml"))
	if code != 1 {
		t.Fatalf("exit = %d, want 1; stderr:\n%s", code, stderr)
	}
	// 契约：`error: <file>: <message>`。
	want := "error: testdata/err-load/bad.yaml: "
	if !strings.Contains(stderr, want) {
		t.Fatalf("error line format mismatch, want prefix %q:\n%s", want, stderr)
	}
	if !strings.Contains(stderr, "strict decode failed") {
		t.Fatalf("unexpected message:\n%s", stderr)
	}
}

func TestCompileErrorFormat(t *testing.T) {
	code, _, stderr := runCLI(t, "compile", "-f", "testdata/err-link", "-o", filepath.Join(t.TempDir(), "x.yaml"))
	if code != 1 {
		t.Fatalf("exit = %d, want 1; stderr:\n%s", code, stderr)
	}
	// 契约：`error: <file>:<kind>/<name>:<path>: <message>`。
	want := "error: testdata/err-link/config.yaml:Route/web:spec.rules[0].backends[0].upstream: "
	if !strings.Contains(stderr, want) {
		t.Fatalf("error line format mismatch, want %q:\n%s", want, stderr)
	}
	if !strings.Contains(stderr, `dangling reference: upstream "ghost" not found`) {
		t.Fatalf("unexpected message:\n%s", stderr)
	}
}

func TestUsageError(t *testing.T) {
	if code, _, _ := runCLI(t); code != 2 {
		t.Fatalf("no args: exit = %d, want 2", code)
	}
	if code, _, _ := runCLI(t, "compile"); code != 2 {
		t.Fatalf("missing -f: exit = %d, want 2", code)
	}
	if code, _, _ := runCLI(t, "bogus"); code != 2 {
		t.Fatalf("unknown command: exit = %d, want 2", code)
	}
	if code, _, _ := runCLI(t, "compile", "-f", "testdata/ok", "--mode", "bogus"); code != 2 {
		t.Fatalf("bad mode: exit = %d, want 2", code)
	}
}

// writeFakeEnvoy 在临时目录写一个可执行的假 envoy 脚本。
func writeFakeEnvoy(t *testing.T, script string) string {
	t.Helper()
	p := filepath.Join(t.TempDir(), "envoy")
	if err := os.WriteFile(p, []byte("#!/bin/sh\n"+script), 0o755); err != nil {
		t.Fatal(err)
	}
	return p
}

func TestEnvoyValidateMissingBinaryIsWarning(t *testing.T) {
	// ESGW_ENVOY_PATH 指向不存在的路径 → F7 降级 Warning，exit 0，产物照常写。
	t.Setenv(envoycheck.EnvVarPath, filepath.Join(t.TempDir(), "nonexistent"))
	out := filepath.Join(t.TempDir(), "envoy.yaml")
	code, _, stderr := runCLI(t, "compile", "-f", "testdata/ok", "-o", out, "--envoy-validate")
	if code != 0 {
		t.Fatalf("exit = %d, want 0 (warning only); stderr:\n%s", code, stderr)
	}
	if !strings.Contains(stderr, "warning: <implicit>: skip envoy --mode validate") {
		t.Fatalf("missing warning line:\n%s", stderr)
	}
	if _, err := os.Stat(out); err != nil {
		t.Fatalf("artifact not written: %v", err)
	}
}

func TestEnvoyValidateFailure(t *testing.T) {
	fake := writeFakeEnvoy(t, `echo "validation failed: bogus" >&2; exit 1`)
	out := filepath.Join(t.TempDir(), "envoy.yaml")
	code, _, stderr := runCLI(t, "compile", "-f", "testdata/ok", "-o", out, "--envoy-validate="+fake)
	if code != 1 {
		t.Fatalf("exit = %d, want 1; stderr:\n%s", code, stderr)
	}
	if !strings.Contains(stderr, "error: <implicit>: envoy --mode validate failed") {
		t.Fatalf("missing error line:\n%s", stderr)
	}
	if !strings.Contains(stderr, "bogus") {
		t.Fatalf("envoy stderr not propagated:\n%s", stderr)
	}
	if _, err := os.Stat(out); !os.IsNotExist(err) {
		t.Fatalf("artifact must not be written on F7 failure")
	}
}

func TestEnvoyValidateXDSModeRendersStatic(t *testing.T) {
	// xds 模式也渲染等价 static 再验（编译层 §3 F7 语义）：假 envoy 断言
	// 收到的文件是 static envoy.yaml（含 static_resources）。
	fake := writeFakeEnvoy(t, `grep -q "static_resources:" "$4" || exit 4`)
	out := filepath.Join(t.TempDir(), "snapshot.json")
	code, _, stderr := runCLI(t, "compile", "-f", "testdata/ok", "--mode", "xds", "-o", out, "--envoy-validate="+fake)
	if code != 0 {
		t.Fatalf("exit = %d; stderr:\n%s", code, stderr)
	}
	if !strings.Contains(stderr, "envoy --mode validate: OK") {
		t.Fatalf("missing OK line:\n%s", stderr)
	}
	// 产物仍是 xds snapshot json。
	b, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	var doc map[string]any
	if err := json.Unmarshal(b, &doc); err != nil {
		t.Fatalf("xds artifact is not JSON: %v", err)
	}
}

func TestVersion(t *testing.T) {
	code, stdout, _ := runCLI(t, "version")
	if code != 0 || !strings.HasPrefix(stdout, "esgw ") {
		t.Fatalf("exit = %d, stdout = %q", code, stdout)
	}
}
